Update schemas
department-of-veterans-affairs/vets-json-schema pull request #834
Opened 2024-01-30 17:23 UTC by ToddWebDev

# New schema

Updates the enums for 21P-527EZ.

[FE update](https://github.com/department-of-veterans-affairs/vets-website/pull/27706)

## Pull Requests to update the schema in related repositories

2024-02-05 17:11 UTC, danlim715 requested changes
@ToddWebDev Just remember to add in the version incrementation in package.json, but other than that, LGTM

2024-02-05 22:28 UTC, danlim715 commented
> @ToddWebDev Just remember to add in the version incrementation in package.json, but other than that, LGTM

nvm, i missed the package.json change in the diff. I'm pushing up some spec fixes, but should be good to go after that.

2024-02-05 22:28 UTC, danlim715 approved these changes

2024-02-05 22:48 UTC, danlim715 approved these changes

2024-02-06 18:16 UTC, ericboehs approved these changes

2024-02-06 19:04 UTC, merged