Local development linking
department-of-veterans-affairs/vets-json-schema pull request #884
Opened 2024-04-16 16:34 UTC by scottsdevelopment

- Add commands for local development linking
- Update documentation on commands
- Remove version.json as it won't be used
- Add license to package json (inferred by vets-api and vets-website) to prevent warning spam

- department-of-veterans-affairs/va.gov-team#79995

2024-04-22 19:34 UTC, wayne-weibel requested changes
Please add a way to test that the local json-schema is being referenced ...

I am seeing an ‘error’ doing unlink and the script is not using the command noted in the output to reinstall the package; would also like this to be in a shell script so it it easier to read and can be annotated

![image](https://github.com/department-of-veterans-affairs/vets-json-schema/assets/5315216/33f3bb3c-2494-4863-83dc-90c127ede840)

2024-04-22 19:34 UTC, wayne-weibel commented on package.json
> +    "link": "yarn link:vets-api; yarn link:vets-website",
use a different name so there is no confusion with the builtin yarn command

2024-04-22 19:34 UTC, wayne-weibel commented on package.json
> +    "link:vets-website": "yarn link; cd ../vets-website; yarn link vets-json-schema",
should move these to a shell script, to keep the package.json cleaner and can annotate the commands

2024-04-25 16:17 UTC, wayne-weibel approved these changes

2024-04-25 18:56 UTC, RachalCassity approved these changes

2024-04-29 15:32 UTC, merged

2025-07-15 17:34 UTC, pmclaren19 commented
@RachalCassity @scottsdevelopment @wayne-weibel trying to follow these instructions here and they are not working. Anyone free to pair?