Added new schema for form 21P-0969 Update Income and Assets
department-of-veterans-affairs/vets-json-schema pull request #899
Opened 2024-05-22 01:49 UTC by danlim715

# New schema
Added a new schema for form 21P-0969 Update Income and Assets Evidence.

Incremented gem version to 22.3.0

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82561

## Pull Requests to update the schema in related repositories

- https://github.com/department-of-veterans-affairs/vets-api/pull/
- https://github.com/department-of-veterans-affairs/vets-website/pull/

2024-05-23 15:38 UTC, wayne-weibel requested changes
One minor change, and some questions
Would like @scottsdevelopment to look this over also, since he is more familiar with json-schema

2024-05-23 15:38 UTC, wayne-weibel commented on test/schemas/21P-0969/schema.spec.js
> +import _ from 'lodash';
possible to import only used functions?

2024-05-29 16:54 UTC, TaiWilkin commented on src/schemas/21P-0969/schema.js
> +    statementOfTruthCertified: {
Should this be a boolean?

2024-05-29 17:17 UTC, danlim715 commented on src/schemas/21P-0969/schema.js
> +    statementOfTruthCertified: {
ah, yes. nice catch!

2024-05-29 18:24 UTC, TaiWilkin approved these changes
Thanks for updating that!

2024-05-29 18:26 UTC, ataker approved these changes

2024-05-29 20:06 UTC, wayne-weibel approved these changes

2024-05-29 20:06 UTC, merged